apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-wcvhbxii
  janus-idp.io/tekton: go-wcvhbxii
  backstage.io/kubernetes-id: go-wcvhbxii
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-wcvhbxii
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
